name: Run benchmark tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bench-tests:
    if: contains(github.event.pull_request.labels.*.name, 'run-benchmark-tests')
    name: Run benchmark tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            lz4/go.sum
            tests/bench/go.sum
            go.sum


      - name: Run benchmark tests
        run: make test-bench
