name: "Docs / Build PR"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs-pr.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"
      - ".github/workflows/docs-pr.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/cache@v5
        # actions/setup-python@v6 poetry cache feature requires poetry to be installed beforehand
        # which makes use of it extremely awkward.
        with:
          path: |
            /home/runner/.cache/pip
            /home/runner/.cache/pypoetry
          # python and poetry version are in docs/pyproject.toml
          key: docs-cache-${{ runner.os }}-${{ hashFiles('docs/pyproject.toml', 'docs/Makefile') }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: docs/pyproject.toml

      - name: Set up env
        run: make -C docs setupenv

      - name: Build docs
        run: make -C docs test